name: CI - Memory Game
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SDL_VIDEODRIVER: dummy
      PYGAME_HIDE_SUPPORT_PROMPT: "1"
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygame pytest flake8
      - name: Lint code
        run: flake8 .
        continue-on-error: true  # quítalo después si quieres que bloquee
      - name: Run unit tests
        run: pytest -q tests
